name = "SeisMakie"
uuid = "1618359f-28d0-421c-9c3d-0705aaf8cc0d"
authors = ["Firas <firas_alchalabi@hotmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
